### ISSUE TITLE
This replica has not yet been checked

### ISSUE THREAD

**Issue by Fever905** [crisp-im/crisp-status-local#2]
Hey, my internal reporting things all say "This replica has not yet been checked"

I'm certain I have the docker image thing setup correctly. I rolled my token and it noticed the token was wrong, so I updated it in the config and the not authorized warning is gone now.

I keep getting these errors over and over

(WARN) - got invalid data for probe map acquire: invalid at line 1 column 459
(WARN) - acquire attempt #0 failed, will retry after delay
(WARN) - got invalid data for probe map acquire: invalid at line 1 column 459
(WARN) - acquire attempt #1 failed, will retry after delay
(WARN) - got invalid data for probe map acquire: invalid at line 1 column 459
(WARN) - probe cycle error in map acquire: ExhaustedAttempts

**Comment by valeriansaliou** [comment]
Hi there!

Which version of `crisp-status-local` are you running? Also, which IP address are you listening on?

I suspect your IP is being blocked by our anti-DDoS system. On the server that runs crisp-status-local, can you run: `curl -i https://report.crisp.watch/v1` and return the result?

**Comment by Fever905** [comment]
Should be the latest version, I installed it last week sometime.  Not sure what IP addresses I am listening on.   I do know it is communicating because when I rolled the API key it said the key was no longer authorized.  I updated the key in my config file and that error message went away.

Results of that run:

root@wc-srv-linux:/# curl -i https://report.crisp.watch/v1
HTTP/1.1 404 Not Found
Date: Tue, 07 Jan 2020 18:09:14 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=dcfc87154d861f1dd77a59a03d5c2548c1578420554; expires=Thu, 06-Feb-20 18:09:14 GMT; path=/; domain=.crisp.watch; HttpOnly; SameSite=Lax
Vary: Accept-Encoding
CF-Cache-Status: DYNAMIC
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Alt-Svc: h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
Server: cloudflare
CF-RAY: 5517e1aefccccacc-YYZ

{"error":true,"reason":"not_found","data":{}}

**Comment by Fever905** [comment]
I do remember that when it was first running I told it to forget something, I can't remember what but there was an option on the monitor status page to forget some result or something.  It may be related to me selecting that option?

**Comment by valeriansaliou** [comment]
Ah, yes. If you rolled the reporter token, then any Crisp Status Local instance configured with the previous reporter token will be put offline. That error was expected, then.

**Comment by Fever905** [comment]
No, the tokens were offline before that.  I only rolled the token to see if it was actually connected.  So how do I get this working?

**Comment by valeriansaliou** [comment]
Is it working now with the new token in your configuration file? I'm confused.

**Comment by Fever905** [comment]
The token was never the issue.  Yes the new token is working but the same errors are being repeated and all 4 of the items report "This replica has not yet been checked" and the terminal where I run the crisp-status-local repeats these 4 warnings over and over:
(WARN) - got invalid data for probe map acquire: invalid at line 1 column 459
(WARN) - acquire attempt #0 failed, will retry after delay
(WARN) - got invalid data for probe map acquire: invalid at line 1 column 459
(WARN) - acquire attempt #1 failed, will retry after delay
(WARN) - got invalid data for probe map acquire: invalid at line 1 column 459
(WARN) - probe cycle error in map acquire: ExhaustedAttempts

**Comment by valeriansaliou** [comment]
I see. This may be an issue w/ HTTP chunked responses. I've released an update yesterday in which I've encountered a similar bug, and managed to fix it. Can you please try to run: https://github.com/crisp-im/crisp-status-local/releases/tag/v1.2.0

This update has also the benefit of not requiring a manual compilation on your end, as I managed to build it in a statically-linked way, which allows the same binary we ship to run on all Linux x64; and also saves a lot of bytes from the final binary.

Let me know if that works w/ 1.2.0. The error you're encountering should be seen right at boot, after waiting for a few seconds, if it occurs.

**Comment by Fever905** [comment]
I updated to 1.2.0 and now I'm seeing this when I run:

(WARN) - failed acquiring probe map: Error: TLS error
(WARN) - acquire attempt #0 failed, will retry after delay
(WARN) - failed acquiring probe map: Error: TLS error
(WARN) - acquire attempt #1 failed, will retry after delay
(WARN) - failed acquiring probe map: Error: TLS error
(WARN) - probe cycle error in map acquire: ExhaustedAttempts

Is there any way I can set a more verbose output to see more detail on what the TLS error is? My openssl is up to date, we run H2 (http2) here without issue.

OpenSSL> version
OpenSSL 1.1.1d  10 Sep 2019

**Comment by valeriansaliou** [comment]
What do the 'date' command output on your server?

**Comment by valeriansaliou** [comment]
Can you try building from source from your server?

**Comment by Fever905** [comment]
root@wc-srv-linux:~# date
Wed Jan  8 09:28:51 EST 2020

**Comment by Fever905** [comment]
Sure i could try that.  Would that still be run through docker or would this run without docker on my server?  Should I try the option 3 first installing from cargo?  I've never used that before but I can give it a go.

**Comment by valeriansaliou** [comment]
Installing the crisp-status-local daemon through cargo is easy; just make sure you run Rust nighly latest (eg. use rustup for that), and then execute: `cargo install crisp-status-local`, which will be then available in your $PATH as a binary under the name of `crisp-status-local`.

**Comment by Fever905** [comment]
Yep I got that cargo installed and it built out the crisp-status-local

Just ran it using the same config file and I'm getting this

(WARN) - got invalid data for probe map acquire: invalid at line 1 column 459
(WARN) - acquire attempt #0 failed, will retry after delay
(WARN) - got invalid data for probe map acquire: invalid at line 1 column 459
(WARN) - acquire attempt #1 failed, will retry after delay
(WARN) - got invalid data for probe map acquire: invalid at line 1 column 459
(WARN) - probe cycle error in map acquire: ExhaustedAttempts

Do you want me to try removing the monitors I setup and adding them again to see if that changes anything?

And the other way you said was to build from the git repo?  Should I try that or would it not make a difference?

**Comment by valeriansaliou** [comment]
That's super weird. Can you please send your private token over to valerian@crisp.chat ? I'll have a test done on my side.

**Comment by valeriansaliou** [comment]
Thanks for the token. I could replicate and find the issue.

Looks like you entered incorrect TCP URLs in the Crisp Status Page options on app.crisp.chat ; your TCP URLs don't have any port set, please ensure each one of them has a port set, in the following format: `tcp://host:port`. As the JSON parser in `crisp-status-local` expects the format to be `tcp://host:port` and not `tcp://host`, it fails parsing with your configuration.

Obviously, there's also an issue in our app, which should have prevented you from inputing such a value. Looks like it used to work in Crisp V2 but broke in our Crisp V3 rework, filing a bug.

Let me know if that fixes :)

**Comment by valeriansaliou** [comment]
By the way, I've released `v1.2.1` which does not depend on OpenSSL anymore. You should be able to run the pre-built binary directly on your system. Can you uninstall the cargo version and use the provided binary now and let me know if that works?

https://github.com/crisp-im/crisp-status-local/releases/tag/v1.2.1

**Comment by Fever905** [comment]
OK I will do that in a couple hours and report back.  Thank you.

**Comment by valeriansaliou** [comment]
Did that work out?

**Comment by Fever905** [comment]
Success!  I edited my TCP watched nodes to use that format you specified as well as updated to the 1.2.1 docker version and it's all working now.   Head's up though - when entering the tcp it does not specify the format in which to enter it.  Probably should add that so we know how the data is expected.

![image](https://user-images.githubusercontent.com/2319655/72160343-2d7fa700-338c-11ea-9c43-fffb97e1bb65.png)

**Comment by valeriansaliou** [comment]
Great! The TCP URL format is shown in the input placeholder before you start entering it, and I've added TCP URL validations before you can save them so that it alerts you if eg. the port is missing, with a clear message.

**Comment by Fever905** [comment]
Awesome, looks great.   Curious, what would happen if you put a http/https URL in there and the URL was returning status 500 (Server/Script Error) instead of the normal 200 (OK).  Would the notifier recognize the 500 status as being bad?  Or even a 404?  Reason I am asking, is that we have an API service setup and last year for a day or two it was down because of a typo in a php file.  We were not aware of what was causing the issue right away.  It would be cool if I could put the URL t my main API endpoint and verify its up and running and coming back 200.

**Comment by valeriansaliou** [comment]
Yes, the notifier is status-aware. It reports as DEAD if the HTTP status code does not match the default success codes (or otherwise, if you've defined an HTTP status range to consider as valid through Crisp App, it would use this range).

See: https://github.com/crisp-im/crisp-status-local/blob/master/src/probe/poll.rs#L217
Default success status ranges are defined here: https://github.com/crisp-im/crisp-status-local/blob/master/src/probe/poll.rs#L26 (200-399 inclusive range).

**Comment by Fever905** [comment]
This is very awesome - thank you I will set this up now.
